/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Huong;

import javax.swing.JOptionPane;

public class UI extends javax.swing.JFrame {
    private SearchTT List;
    /**
     * Creates new form UI
     */
    public UI() {
        this.setTitle("Sequential Search");
        this.setLocationRelativeTo(null);
        this.setSize(1200, 800);
        drawArray1 = new DrawArray();
        List = new SearchTT();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        Random = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        inputNumber = new javax.swing.JTextField();
        drawArray1 = new Huong.DrawArray();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Random.setForeground(new java.awt.Color(32, 209, 52));
        Random.setText("Random");
        Random.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRandom(evt);
            }
        });
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        Add.setForeground(new java.awt.Color(229, 30, 30));
        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAdd(evt);
            }
        });

        Search.setForeground(new java.awt.Color(229, 178, 32));
        Search.setText("Search");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSearch(evt);
            }
        });

        Delete.setForeground(new java.awt.Color(49, 30, 227));
        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickDelete(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Random, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Random)
                    .addComponent(Search)
                    .addComponent(Delete)
                    .addComponent(inputNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add))
                .addContainerGap())
        );

        javax.swing.GroupLayout drawArray1Layout = new javax.swing.GroupLayout(drawArray1);
        drawArray1.setLayout(drawArray1Layout);
        drawArray1Layout.setHorizontalGroup(
            drawArray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawArray1Layout.setVerticalGroup(
            drawArray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawArray1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawArray1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickRandom(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRandom

        List.insertNode((int)(Math.random()*100) + 1);
        drawArray1.repaint();
    }//GEN-LAST:event_clickRandom

    private void clickAdd(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAdd
        // TODO add your handling code here:
        int number;
        try{
            number = Integer.parseInt(inputNumber.getText());
        }catch(NumberFormatException e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ban Chua Nhap Vao Gia Tri.!");
            return;
        }
        List.insertNode(number);
        drawArray1.repaint();
    }//GEN-LAST:event_clickAdd

    private void clickSearch(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSearch
        // TODO add your handling code here:
        int number;
        try {
            number = Integer.parseInt(inputNumber.getText());
        } catch(NumberFormatException e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ban Chua Nhap Vao Gia Tri.!");
            return;
        }
        Node x=List.searchTT(number);
        if(x != null){
        drawArray1.startAction();
        int a= x.getX() / 60;
        JOptionPane.showMessageDialog(null, "Tim thay gia tri "+ number+" tai vi tri thu "+ a+" cua mang");
          }else{
           
            drawArray1.repaint();
            List.deleteNode(SearchTT.getIndexSearch());
            JOptionPane.showMessageDialog(null, "Khong tim thay gia tri :"+ number+" trong mang");
            return;
        }
    }//GEN-LAST:event_clickSearch

    private void clickDelete(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickDelete
        // TODO add your handling code here:
        int number;
        try{
            number = Integer.parseInt(inputNumber.getText());
        } catch (NumberFormatException e){
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ban Chua Nhap Vao Gia Tri.!");
            return;
        }
        Node x = List.searchTT(number); 
        if(x != null){
        drawArray1.repaint();
        List.deleteNode(SearchTT.getIndexSearch());
        int a= x.getX() / 60;
        JOptionPane.showMessageDialog(null, "Da xoa gia tri "+ number+" tai vi tri thu "+ a+" cua mang");
        } else{
            JOptionPane.showMessageDialog(null, "Khong tim thay gia tri :"+ number);
            return;
        }
                
    }//GEN-LAST:event_clickDelete

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Random;
    private javax.swing.JButton Search;
    private Huong.DrawArray drawArray1;
    private javax.swing.JPanel header;
    private javax.swing.JTextField inputNumber;
    // End of variables declaration//GEN-END:variables

}
